export const errorCodesEnum = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  GEOSERVER_HOST_NOT_ALLOWED: 'GEOSERVER_HOST_NOT_ALLOWED',
  INVALID_GEOSERVER_URL: 'INVALID_GEOSERVER_URL',
  MISSING_GEOSERVER_BASEURL: 'MISSING_GEOSERVER_BASEURL',
  GEOSERVER_UNREACHABLE: 'GEOSERVER_UNREACHABLE',
} as const
