export const errorCodesEnum = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  GEOSERVER_HOST_NOT_ALLOWED: 'GEOSERVER_HOST_NOT_ALLOWED',
} as const
